# coding: utf-8

"""


    Generated by: https://openapi-generator.tech
"""

from dataclasses import dataclass
import typing_extensions
import urllib3
from urllib3._collections import HTTPHeaderDict

from openapi_client import api_client, exceptions
from datetime import date, datetime  # noqa: F401
import decimal  # noqa: F401
import functools  # noqa: F401
import io  # noqa: F401
import re  # noqa: F401
import typing  # noqa: F401
import typing_extensions  # noqa: F401
import uuid  # noqa: F401

import frozendict  # noqa: F401

from openapi_client import schemas  # noqa: F401

from openapi_client.model.error_info import ErrorInfo
from openapi_client.model.mission import Mission
from openapi_client.model.category_cd import CategoryCd
from openapi_client.model.law_num_type import LawNumType
from openapi_client.model.law_num_era import LawNumEra
from openapi_client.model.response_format import ResponseFormat
from openapi_client.model.law_type import LawType
from openapi_client.model.laws_response import LawsResponse
from openapi_client.model.repeal_status import RepealStatus

# Query params
LawIdSchema = schemas.StrSchema
LawNumSchema = schemas.StrSchema
LawNumEraSchema = LawNumEra
LawNumNumSchema = schemas.StrSchema
LawNumTypeSchema = LawNumType
LawNumYearSchema = schemas.IntSchema
LawTitleSchema = schemas.StrSchema
LawTitleKanaSchema = schemas.StrSchema


class LawTypeSchema(
    schemas.ListSchema
):


    class MetaOapg:
        
        @staticmethod
        def items() -> typing.Type['LawType']:
            return LawType

    def __new__(
        cls,
        _arg: typing.Union[typing.Tuple['LawType'], typing.List['LawType']],
        _configuration: typing.Optional[schemas.Configuration] = None,
    ) -> 'LawTypeSchema':
        return super().__new__(
            cls,
            _arg,
            _configuration=_configuration,
        )

    def __getitem__(self, i: int) -> 'LawType':
        return super().__getitem__(i)
AmendmentLawIdSchema = schemas.StrSchema
AsofSchema = schemas.DateSchema


class CategoryCdSchema(
    schemas.ListSchema
):


    class MetaOapg:
        
        @staticmethod
        def items() -> typing.Type['CategoryCd']:
            return CategoryCd

    def __new__(
        cls,
        _arg: typing.Union[typing.Tuple['CategoryCd'], typing.List['CategoryCd']],
        _configuration: typing.Optional[schemas.Configuration] = None,
    ) -> 'CategoryCdSchema':
        return super().__new__(
            cls,
            _arg,
            _configuration=_configuration,
        )

    def __getitem__(self, i: int) -> 'CategoryCd':
        return super().__getitem__(i)


class MissionSchema(
    schemas.ListSchema
):


    class MetaOapg:
        
        @staticmethod
        def items() -> typing.Type['Mission']:
            return Mission

    def __new__(
        cls,
        _arg: typing.Union[typing.Tuple['Mission'], typing.List['Mission']],
        _configuration: typing.Optional[schemas.Configuration] = None,
    ) -> 'MissionSchema':
        return super().__new__(
            cls,
            _arg,
            _configuration=_configuration,
        )

    def __getitem__(self, i: int) -> 'Mission':
        return super().__getitem__(i)
OmitCurrentRevisionInfoSchema = schemas.BoolSchema
PromulgationDateFromSchema = schemas.DateSchema
PromulgationDateToSchema = schemas.DateSchema


class RepealStatusSchema(
    schemas.ListSchema
):


    class MetaOapg:
        
        @staticmethod
        def items() -> typing.Type['RepealStatus']:
            return RepealStatus

    def __new__(
        cls,
        _arg: typing.Union[typing.Tuple['RepealStatus'], typing.List['RepealStatus']],
        _configuration: typing.Optional[schemas.Configuration] = None,
    ) -> 'RepealStatusSchema':
        return super().__new__(
            cls,
            _arg,
            _configuration=_configuration,
        )

    def __getitem__(self, i: int) -> 'RepealStatus':
        return super().__getitem__(i)
LimitSchema = schemas.Int32Schema
OffsetSchema = schemas.Int32Schema
OrderSchema = schemas.StrSchema


class ResponseFormatSchema(
    schemas.ComposedSchema,
):


    class MetaOapg:
        
        @classmethod
        @functools.lru_cache()
        def all_of(cls):
            # we need this here to make our import statements work
            # we must store _composed_schemas in here so the code is only run
            # when we invoke this method. If we kept this at the class
            # level we would get an error because the class level
            # code would be run when this module is imported, and these composed
            # classes don't exist yet because their module has not finished
            # loading
            return [
                ResponseFormat,
            ]


    def __new__(
        cls,
        *_args: typing.Union[dict, frozendict.frozendict, str, date, datetime, uuid.UUID, int, float, decimal.Decimal, bool, None, list, tuple, bytes, io.FileIO, io.BufferedReader, ],
        _configuration: typing.Optional[schemas.Configuration] = None,
        **kwargs: typing.Union[schemas.AnyTypeSchema, dict, frozendict.frozendict, str, date, datetime, uuid.UUID, int, float, decimal.Decimal, None, list, tuple, bytes],
    ) -> 'ResponseFormatSchema':
        return super().__new__(
            cls,
            *_args,
            _configuration=_configuration,
            **kwargs,
        )
RequestRequiredQueryParams = typing_extensions.TypedDict(
    'RequestRequiredQueryParams',
    {
    }
)
RequestOptionalQueryParams = typing_extensions.TypedDict(
    'RequestOptionalQueryParams',
    {
        'law_id': typing.Union[LawIdSchema, str, ],
        'law_num': typing.Union[LawNumSchema, str, ],
        'law_num_era': typing.Union[LawNumEraSchema, ],
        'law_num_num': typing.Union[LawNumNumSchema, str, ],
        'law_num_type': typing.Union[LawNumTypeSchema, ],
        'law_num_year': typing.Union[LawNumYearSchema, decimal.Decimal, int, ],
        'law_title': typing.Union[LawTitleSchema, str, ],
        'law_title_kana': typing.Union[LawTitleKanaSchema, str, ],
        'law_type': typing.Union[LawTypeSchema, list, tuple, ],
        'amendment_law_id': typing.Union[AmendmentLawIdSchema, str, ],
        'asof': typing.Union[AsofSchema, str, date, ],
        'category_cd': typing.Union[CategoryCdSchema, list, tuple, ],
        'mission': typing.Union[MissionSchema, list, tuple, ],
        'omit_current_revision_info': typing.Union[OmitCurrentRevisionInfoSchema, bool, ],
        'promulgation_date_from': typing.Union[PromulgationDateFromSchema, str, date, ],
        'promulgation_date_to': typing.Union[PromulgationDateToSchema, str, date, ],
        'repeal_status': typing.Union[RepealStatusSchema, list, tuple, ],
        'limit': typing.Union[LimitSchema, decimal.Decimal, int, ],
        'offset': typing.Union[OffsetSchema, decimal.Decimal, int, ],
        'order': typing.Union[OrderSchema, str, ],
        'response_format': typing.Union[ResponseFormatSchema, dict, frozendict.frozendict, str, date, datetime, uuid.UUID, int, float, decimal.Decimal, bool, None, list, tuple, bytes, io.FileIO, io.BufferedReader, ],
    },
    total=False
)


class RequestQueryParams(RequestRequiredQueryParams, RequestOptionalQueryParams):
    pass


request_query_law_id = api_client.QueryParameter(
    name="law_id",
    style=api_client.ParameterStyle.FORM,
    schema=LawIdSchema,
    explode=True,
)
request_query_law_num = api_client.QueryParameter(
    name="law_num",
    style=api_client.ParameterStyle.FORM,
    schema=LawNumSchema,
    explode=True,
)
request_query_law_num_era = api_client.QueryParameter(
    name="law_num_era",
    style=api_client.ParameterStyle.FORM,
    schema=LawNumEraSchema,
    explode=True,
)
request_query_law_num_num = api_client.QueryParameter(
    name="law_num_num",
    style=api_client.ParameterStyle.FORM,
    schema=LawNumNumSchema,
    explode=True,
)
request_query_law_num_type = api_client.QueryParameter(
    name="law_num_type",
    style=api_client.ParameterStyle.FORM,
    schema=LawNumTypeSchema,
    explode=True,
)
request_query_law_num_year = api_client.QueryParameter(
    name="law_num_year",
    style=api_client.ParameterStyle.FORM,
    schema=LawNumYearSchema,
    explode=True,
)
request_query_law_title = api_client.QueryParameter(
    name="law_title",
    style=api_client.ParameterStyle.FORM,
    schema=LawTitleSchema,
    explode=True,
)
request_query_law_title_kana = api_client.QueryParameter(
    name="law_title_kana",
    style=api_client.ParameterStyle.FORM,
    schema=LawTitleKanaSchema,
    explode=True,
)
request_query_law_type = api_client.QueryParameter(
    name="law_type",
    style=api_client.ParameterStyle.FORM,
    schema=LawTypeSchema,
)
request_query_amendment_law_id = api_client.QueryParameter(
    name="amendment_law_id",
    style=api_client.ParameterStyle.FORM,
    schema=AmendmentLawIdSchema,
    explode=True,
)
request_query_asof = api_client.QueryParameter(
    name="asof",
    style=api_client.ParameterStyle.FORM,
    schema=AsofSchema,
    explode=True,
)
request_query_category_cd = api_client.QueryParameter(
    name="category_cd",
    style=api_client.ParameterStyle.FORM,
    schema=CategoryCdSchema,
)
request_query_mission = api_client.QueryParameter(
    name="mission",
    style=api_client.ParameterStyle.FORM,
    schema=MissionSchema,
)
request_query_omit_current_revision_info = api_client.QueryParameter(
    name="omit_current_revision_info",
    style=api_client.ParameterStyle.FORM,
    schema=OmitCurrentRevisionInfoSchema,
    explode=True,
)
request_query_promulgation_date_from = api_client.QueryParameter(
    name="promulgation_date_from",
    style=api_client.ParameterStyle.FORM,
    schema=PromulgationDateFromSchema,
    explode=True,
)
request_query_promulgation_date_to = api_client.QueryParameter(
    name="promulgation_date_to",
    style=api_client.ParameterStyle.FORM,
    schema=PromulgationDateToSchema,
    explode=True,
)
request_query_repeal_status = api_client.QueryParameter(
    name="repeal_status",
    style=api_client.ParameterStyle.FORM,
    schema=RepealStatusSchema,
)
request_query_limit = api_client.QueryParameter(
    name="limit",
    style=api_client.ParameterStyle.FORM,
    schema=LimitSchema,
    explode=True,
)
request_query_offset = api_client.QueryParameter(
    name="offset",
    style=api_client.ParameterStyle.FORM,
    schema=OffsetSchema,
    explode=True,
)
request_query_order = api_client.QueryParameter(
    name="order",
    style=api_client.ParameterStyle.FORM,
    schema=OrderSchema,
)
request_query_response_format = api_client.QueryParameter(
    name="response_format",
    style=api_client.ParameterStyle.FORM,
    schema=ResponseFormatSchema,
    explode=True,
)
SchemaFor200ResponseBodyApplicationJson = LawsResponse
SchemaFor200ResponseBodyApplicationXml = LawsResponse


@dataclass
class ApiResponseFor200(api_client.ApiResponse):
    response: urllib3.HTTPResponse
    body: typing.Union[
        SchemaFor200ResponseBodyApplicationJson,
        SchemaFor200ResponseBodyApplicationXml,
    ]
    headers: schemas.Unset = schemas.unset


_response_for_200 = api_client.OpenApiResponse(
    response_cls=ApiResponseFor200,
    content={
        'application/json': api_client.MediaType(
            schema=SchemaFor200ResponseBodyApplicationJson),
        'application/xml': api_client.MediaType(
            schema=SchemaFor200ResponseBodyApplicationXml),
    },
)
SchemaFor400ResponseBodyApplicationJson = ErrorInfo
SchemaFor400ResponseBodyApplicationXml = ErrorInfo


@dataclass
class ApiResponseFor400(api_client.ApiResponse):
    response: urllib3.HTTPResponse
    body: typing.Union[
        SchemaFor400ResponseBodyApplicationJson,
        SchemaFor400ResponseBodyApplicationXml,
    ]
    headers: schemas.Unset = schemas.unset


_response_for_400 = api_client.OpenApiResponse(
    response_cls=ApiResponseFor400,
    content={
        'application/json': api_client.MediaType(
            schema=SchemaFor400ResponseBodyApplicationJson),
        'application/xml': api_client.MediaType(
            schema=SchemaFor400ResponseBodyApplicationXml),
    },
)
SchemaFor500ResponseBodyApplicationJson = ErrorInfo
SchemaFor500ResponseBodyApplicationXml = ErrorInfo


@dataclass
class ApiResponseFor500(api_client.ApiResponse):
    response: urllib3.HTTPResponse
    body: typing.Union[
        SchemaFor500ResponseBodyApplicationJson,
        SchemaFor500ResponseBodyApplicationXml,
    ]
    headers: schemas.Unset = schemas.unset


_response_for_500 = api_client.OpenApiResponse(
    response_cls=ApiResponseFor500,
    content={
        'application/json': api_client.MediaType(
            schema=SchemaFor500ResponseBodyApplicationJson),
        'application/xml': api_client.MediaType(
            schema=SchemaFor500ResponseBodyApplicationXml),
    },
)
_all_accept_content_types = (
    'application/json',
    'application/xml',
)


class BaseApi(api_client.Api):
    @typing.overload
    def _get_laws_oapg(
        self,
        query_params: RequestQueryParams = frozendict.frozendict(),
        accept_content_types: typing.Tuple[str] = _all_accept_content_types,
        stream: bool = False,
        timeout: typing.Optional[typing.Union[int, typing.Tuple]] = None,
        skip_deserialization: typing_extensions.Literal[False] = ...,
    ) -> typing.Union[
        ApiResponseFor200,
    ]: ...

    @typing.overload
    def _get_laws_oapg(
        self,
        skip_deserialization: typing_extensions.Literal[True],
        query_params: RequestQueryParams = frozendict.frozendict(),
        accept_content_types: typing.Tuple[str] = _all_accept_content_types,
        stream: bool = False,
        timeout: typing.Optional[typing.Union[int, typing.Tuple]] = None,
    ) -> api_client.ApiResponseWithoutDeserialization: ...

    @typing.overload
    def _get_laws_oapg(
        self,
        query_params: RequestQueryParams = frozendict.frozendict(),
        accept_content_types: typing.Tuple[str] = _all_accept_content_types,
        stream: bool = False,
        timeout: typing.Optional[typing.Union[int, typing.Tuple]] = None,
        skip_deserialization: bool = ...,
    ) -> typing.Union[
        ApiResponseFor200,
        api_client.ApiResponseWithoutDeserialization,
    ]: ...

    def _get_laws_oapg(
        self,
        query_params: RequestQueryParams = frozendict.frozendict(),
        accept_content_types: typing.Tuple[str] = _all_accept_content_types,
        stream: bool = False,
        timeout: typing.Optional[typing.Union[int, typing.Tuple]] = None,
        skip_deserialization: bool = False,
    ):
        """
        法令一覧取得API
        :param skip_deserialization: If true then api_response.response will be set but
            api_response.body and api_response.headers will not be deserialized into schema
            class instances
        """
        self._verify_typed_dict_inputs_oapg(RequestQueryParams, query_params)
        used_path = path.value

        prefix_separator_iterator = None
        for parameter in (
            request_query_law_id,
            request_query_law_num,
            request_query_law_num_era,
            request_query_law_num_num,
            request_query_law_num_type,
            request_query_law_num_year,
            request_query_law_title,
            request_query_law_title_kana,
            request_query_law_type,
            request_query_amendment_law_id,
            request_query_asof,
            request_query_category_cd,
            request_query_mission,
            request_query_omit_current_revision_info,
            request_query_promulgation_date_from,
            request_query_promulgation_date_to,
            request_query_repeal_status,
            request_query_limit,
            request_query_offset,
            request_query_order,
            request_query_response_format,
        ):
            parameter_data = query_params.get(parameter.name, schemas.unset)
            if parameter_data is schemas.unset:
                continue
            if prefix_separator_iterator is None:
                prefix_separator_iterator = parameter.get_prefix_separator_iterator()
            serialized_data = parameter.serialize(parameter_data, prefix_separator_iterator)
            for serialized_value in serialized_data.values():
                used_path += serialized_value

        _headers = HTTPHeaderDict()
        # TODO add cookie handling
        if accept_content_types:
            for accept_content_type in accept_content_types:
                _headers.add('Accept', accept_content_type)

        response = self.api_client.call_api(
            resource_path=used_path,
            method='get'.upper(),
            headers=_headers,
            stream=stream,
            timeout=timeout,
        )

        if skip_deserialization:
            api_response = api_client.ApiResponseWithoutDeserialization(response=response)
        else:
            response_for_status = _status_code_to_response.get(str(response.status))
            if response_for_status:
                api_response = response_for_status.deserialize(response, self.api_client.configuration)
            else:
                api_response = api_client.ApiResponseWithoutDeserialization(response=response)

        if not 200 <= response.status <= 299:
            raise exceptions.ApiException(
                status=response.status,
                reason=response.reason,
                api_response=api_response
            )

        return api_response


class GetLaws(BaseApi):
    # this class is used by api classes that refer to endpoints with operationId fn names

    @typing.overload
    def get_laws(
        self,
        query_params: RequestQueryParams = frozendict.frozendict(),
        accept_content_types: typing.Tuple[str] = _all_accept_content_types,
        stream: bool = False,
        timeout: typing.Optional[typing.Union[int, typing.Tuple]] = None,
        skip_deserialization: typing_extensions.Literal[False] = ...,
    ) -> typing.Union[
        ApiResponseFor200,
    ]: ...

    @typing.overload
    def get_laws(
        self,
        skip_deserialization: typing_extensions.Literal[True],
        query_params: RequestQueryParams = frozendict.frozendict(),
        accept_content_types: typing.Tuple[str] = _all_accept_content_types,
        stream: bool = False,
        timeout: typing.Optional[typing.Union[int, typing.Tuple]] = None,
    ) -> api_client.ApiResponseWithoutDeserialization: ...

    @typing.overload
    def get_laws(
        self,
        query_params: RequestQueryParams = frozendict.frozendict(),
        accept_content_types: typing.Tuple[str] = _all_accept_content_types,
        stream: bool = False,
        timeout: typing.Optional[typing.Union[int, typing.Tuple]] = None,
        skip_deserialization: bool = ...,
    ) -> typing.Union[
        ApiResponseFor200,
        api_client.ApiResponseWithoutDeserialization,
    ]: ...

    def get_laws(
        self,
        query_params: RequestQueryParams = frozendict.frozendict(),
        accept_content_types: typing.Tuple[str] = _all_accept_content_types,
        stream: bool = False,
        timeout: typing.Optional[typing.Union[int, typing.Tuple]] = None,
        skip_deserialization: bool = False,
    ):
        return self._get_laws_oapg(
            query_params=query_params,
            accept_content_types=accept_content_types,
            stream=stream,
            timeout=timeout,
            skip_deserialization=skip_deserialization
        )


class ApiForget(BaseApi):
    # this class is used by api classes that refer to endpoints by path and http method names

    @typing.overload
    def get(
        self,
        query_params: RequestQueryParams = frozendict.frozendict(),
        accept_content_types: typing.Tuple[str] = _all_accept_content_types,
        stream: bool = False,
        timeout: typing.Optional[typing.Union[int, typing.Tuple]] = None,
        skip_deserialization: typing_extensions.Literal[False] = ...,
    ) -> typing.Union[
        ApiResponseFor200,
    ]: ...

    @typing.overload
    def get(
        self,
        skip_deserialization: typing_extensions.Literal[True],
        query_params: RequestQueryParams = frozendict.frozendict(),
        accept_content_types: typing.Tuple[str] = _all_accept_content_types,
        stream: bool = False,
        timeout: typing.Optional[typing.Union[int, typing.Tuple]] = None,
    ) -> api_client.ApiResponseWithoutDeserialization: ...

    @typing.overload
    def get(
        self,
        query_params: RequestQueryParams = frozendict.frozendict(),
        accept_content_types: typing.Tuple[str] = _all_accept_content_types,
        stream: bool = False,
        timeout: typing.Optional[typing.Union[int, typing.Tuple]] = None,
        skip_deserialization: bool = ...,
    ) -> typing.Union[
        ApiResponseFor200,
        api_client.ApiResponseWithoutDeserialization,
    ]: ...

    def get(
        self,
        query_params: RequestQueryParams = frozendict.frozendict(),
        accept_content_types: typing.Tuple[str] = _all_accept_content_types,
        stream: bool = False,
        timeout: typing.Optional[typing.Union[int, typing.Tuple]] = None,
        skip_deserialization: bool = False,
    ):
        return self._get_laws_oapg(
            query_params=query_params,
            accept_content_types=accept_content_types,
            stream=stream,
            timeout=timeout,
            skip_deserialization=skip_deserialization
        )


